# Generated by Django 5.2.5 on 2025-08-07 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('knit', 'Knitting'), ('crochet', 'Crochet')], max_length=10)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('needle_or_hook_size', models.CharField(blank=True, max_length=50)),
                ('pattern_link', models.URLField(blank=True)),
                ('pattern_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=50)),
                ('amount_per_skein', models.CharField(max_length=50)),
                ('product_link', models.URLField(blank=True)),
                ('material', models.CharField(blank=True, help_text='Fiber content, e.g. Wool, Cotton, Acrylic, etc.', max_length=100)),
                ('quantity_owned_skeins', models.DecimalField(blank=True, decimal_places=2, help_text='How many skeins of this yarn you own (optional)', max_digits=5, null=True)),
                ('quantity_owned_grams', models.DecimalField(blank=True, decimal_places=2, help_text='How many grams of this yarn you own (optional)', max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rows_completed', models.PositiveIntegerField()),
                ('stitches_completed', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
        migrations.CreateModel(
            name='ProjectYarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used_skeins', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity_used_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarns', to='api.project')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_usages', to='api.yarn')),
            ],
        ),
    ]
