# Generated by Django 5.2.5 on 2025-08-08 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
