# Generated by Django 5.2.5 on 2025-08-09 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_projectprogress_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='colour',
            field=models.CharField(help_text='Enter a hex colour code, e.g. #AABBCC', max_length=7, validators=[django.core.validators.RegexValidator(message='Colour must be a valid hex code (e.g., #A1B2C3)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
