# Generated by Django 5.2.5 on 2025-08-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_main_image_progressimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='quantity_owned_grams',
        ),
    ]
