# Generated by Django 5.2.5 on 2025-08-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_yarn_quantity_owned_grams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='yarn',
            name='colour_name',
            field=models.CharField(blank=True, help_text="Colour printed on the label, e.g. 'Sky Blue'", max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
