# Generated by Django 5.2.5 on 2025-08-16 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_project_user_alter_tag_user_alter_yarn_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_project_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='projectyarn',
            constraint=models.UniqueConstraint(fields=('project', 'yarn'), name='uniq_project_yarn_pair'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_tag_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='yarn',
            constraint=models.UniqueConstraint(fields=('user', 'brand', 'weight', 'colour', 'material', 'amount_per_skein'), name='uniq_yarn_signature_per_user'),
        ),
    ]
